---
# tasks file for sbaerlocher.powercfg

- block:
    - name: disable hibernation
      win_shell: powercfg.exe /hibernate off
      when: powercfg_hibernation_disable | bool

    - name: enable hibernation
      win_shell: powercfg.exe /hibernate on
      when: not powercfg_hibernation_disable | bool

    - name: disable standby
      win_shell: powercfg -change -standby-timeout-ac 0
      when: powercfg_standby_ac_disable | bool

    - name: enable standby
      win_shell: 'powercfg -change -standby-timeout-ac {{ powercfg_standby_ac_time }}'
      when: not powercfg_standby_ac_disable | bool

  when: >
    not (ansible_system_vendor == "QEMU")
