---
# tasks file for sbaerlocher.powercfg

- name: disable hibernation
  win_shell: powercfg.exe /hibernate off
  when: not hibernation

- name: enable hibernation
  win_shell: powercfg.exe /hibernate on
  when: hibernation
